export const endPoint =
    import.meta.env.VITE_APP_API_URL ?? "http://localhost:5050";

export default {
    GET: {
        ADDRESS: "/address",
        ADD_SOCIAL_USER: "/user/new/social",
        CONTACTS: "/user/contacts",
        TAGS: "/user/tags/{tags}",
        SHARE_INFO: "/share/item/{id}",
        LIKE_KEYWORD_LIST: "/search/keywords/{keyword}",
        SEARCH_RESULT: "/search/results/{keyword}",
        RECENT_SEARCH_KEYWORD_LIST: "/search/recent",
        MY_SHARE_LIST: "/share/list/my",
        STARRED_SHARE_LIST: "/share/list/starred",
        ADMIN_INFO_LIST_BY_TAG: "/admin/info/tag",
    },
    POST: {
        LOGIN_BY_EMAIL: "/login/email",
        LOGIN_BY_SOCIAL: "/login/social",
        LOGIN_BY_TOKEN: "/login/token",
        VERIFY_EMAIL: "/verify/email/token",
        MAKE_EMAIL_VERIFIED: "/verify/email",
        ADD_USER: "/user/new",
        ADD_SOCIAL_USER: "/user/new/social",
        LOGOUT: "/logout",
        CHECK_CURRENT_USER_PASSWORD: "/user/password",
        ADD_SHARE_INFO: "/share/add",
        GET_SHARE_INFOS_WITH_MAP_BOUNDS: "/share/list",
        ADD_RECENT_SEARCH_KEYWORD: "/search/recent",
        ADD_SHARE_STAR: "/share/star",
        CHANGE_ADMIN_STATUS: "/share/admin",
        UPDATE_COMPLEXED_SHARED: "/share/complexed",
        SEND_CHANGE_PASSWORD_MAIL: "/password/change",
    },
    PATCH: {
        UPDATE_NICKNAME: "/user/nickname",
        UPDATE_PASSWORD: "/user/password",
        UPDATE_PASSWORD_WITH_TOKEN: "/user/password/token",
        UPDATE_CONTACTS: "/user/contacts",
        UPDATE_SHARE_STATUS: "/share/status/{id}",
        UPDATE_SAHRE_GOODS_QUANTITY: "/share/goods/quantity/{id}",
        UPDATE_SHARE_NAME: "/share/name/{id}",
        UPDATE_SHARE_POINT: "/share/point/{id}",
        UPDATE_SHARE_GOODS: "/share/goods/{id}",
        UPDATE_SHARE_CONTACTS: "/share/contacts/{id}",
        UPDATE_SHARE_ADMINS: "/share/admins/{id}",
    },
    DELETE: {
        DELETE_RECENT_SEARCH_KEYWORD: "/search/recent/{id}",
        DELETE_ALL_RECENT_SEARCH_KEYWORD: "/search/recent_all",
        DELETE_SHARE: "/share/{id}",
        DELETE_SHARES: "/shares/{ids}",
        USER: "/user",
    },
};
