name: nanumsa CI kustomize

on:
    workflow_call:
        inputs:
            image-name:
                description: "Name of the image to be updated"
                required: true
                default: "nanumsa-front"
                type: string
            new-version:
                description: "New Deploy Version"
                required: true
                default: "0.0.0"
                type: string

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Setup Kustomize
              uses: imranismail/setup-kustomize@v1

            - name: Checkout Kustomize repository
              uses: actions/checkout@v2

            - name: Checkout k8s Project repository
              uses: actions/checkout@v4
              with:
                  repository: SmileMeeso/nanumsa-k8s
                  path: nanumsa-k8s

            - name: Update image in kustomization
              run: |
                  image_name="${{ inputs.image-name }}"
                  modified_name=${image_name/nanumsa-/}
                  combined_path="./nanumsa-k8s/${modified_name}"
                  cd "$combined_path"

                  echo "new version: ${{ inputs.new-version }}"

                  kustomize edit set image ${{ inputs.image_name }}=${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ inputs.new-version }}
                  kustomize edit set namespace default

            - name: Kustomize Build
              run: |
                  image_name="${{ inputs.image-name }}"
                  modified_name=${image_name/nanumsa-/}
                  combined_path="./nanumsa-k8s/${modified_name}"
                  cd "$combined_path"

                  kustomize build . > kustomized-all.yaml
                  cat kustomized-all.yaml

            - name: Apply Deployment
              run: |
                  image_name="${{ inputs.image-name }}"
                  modified_name=${image_name/nanumsa-/}
                  combined_path="./nanumsa-k8s/${modified_name}"
                  cd "$combined_path"

                  yq -sy '.[1]' ./kustomized-all.yaml > ./kustomized-development.yaml
                  cat kustomized-development.yaml

                  kubectl apply -f <(yq select(document_index == 1) ./kustomized-all.yaml)

            - name: Change Deployment to New Deployment File
              run: |
                  image_name="${{ inputs.image-name }}"
                  modified_name=${image_name/nanumsa-/}
                  combined_path="./nanumsa-k8s/${modified_name}"
                  cd "$combined_path"

                  mv kustomized-deployment.yaml deployment.yaml
                  cat deployment.yaml

            - uses: actions/checkout@v2
              with:
                  repository: SmileMeeso/nanumsa-k8s
                  ref: "main"
                  token: ${{ secrets.PUSH_K8S_TOKEN }}

            - name: Commit changes
              run: |
                  ls -l

                  image_name="${{ inputs.image-name }}"
                  folder_name="${image_name/nanumsa-/}"

                  echo "$folder_name/deployment.yaml"
                  cat $folder_name/deployment.yaml

                  git config user.name ${{ secrets.USER_NAME }}
                  git config user.email ${{ secrets.EMAIL }}
                  git commit -m "Update Kustomization with new version: ${{ inputs.new-version }}" || echo "No changes to commit."
                  git push origin main

            - name: Clean up workspace
              run: |
                  cd ~/actions-runner/_work
                  rm -rf nanumsa-k8s
