name: nanumsa CI kustomize

on:
    workflow_call:
        inputs:
            image-name:
                description: "Name of the image to be updated"
                required: true
                default: "nanumsa-front"
                type: string
            new-version:
                description: "New Deploy Version"
                required: true
                default: "0.0.0"
                type: string

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Setup Kustomize
              uses: imranismail/setup-kustomize@v1

            - name: Checkout Kustomize repository
              uses: actions/checkout@v2

            - name: Checkout k8s Project repository
              uses: actions/checkout@v4
              with:
                  repository: SmileMeeso/nanumsa-k8s
                  path: nanumsa-k8s

            - name: Edit Update Image Tag in Kustomization
              run: |
                  echo "${{image_name/nanumsa-}}"
                  ls -l ./nanumsa-k8s/
                  image_name="${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}"
                  folder_name="./nanumsa-k8s/${image_name/nanumsa-/}"

                  cd $folder_name

                  yq eval ".images[0].name = \"${image_name}:${new-version}\"" -i $folder_name/kustomization.yaml

            - name: Kustomize Build"
              uses: karancode/kustomize-github-action@master
              with:
                  kustomize_version: "${{ inputs.new-version }}"
                  kustomize_build_dir: "./nanumsa-k8s/${image_name/nanumsa-/}"
                  kustomize_comment: true
                  kustomize_output_file: "./nanumsa-k8s/${image_name/nanumsa-/}/kustomized-deployment.yaml"
              env:
                  GITHUB_ACCESS_TOKEN: ${{ secrets.PUSH_K8S_TOKEN }}

            - name: Change Deployment to New Deployment File
              run: |
                  mv ./nanumsa-k8s/${image_name/nanumsa-/}/deployment.yaml ./nanumsa-k8s/${image_name/nanumsa-/}/kustomized-deployment.yaml

            - uses: actions/checkout@v2
              with:
                  repository: SmileMeeso/nanumsa-k8s
                  ref: "main"
                  token: ${{ secrets.PUSH_K8S_TOKEN }}

            - name: Commit changes
              run: |
                  ls -l

                  image_name="${{ inputs.image-name }}"
                  folder_name="${image_name/nanumsa-/}"

                  echo "$folder_name/deployment.yaml"
                  cat $folder_name/deployment.yaml

                  git config user.name ${{ secrets.USER_NAME }}
                  git config user.email ${{ secrets.EMAIL }}
                  git commit -m "Update Kustomization with new version: ${{ inputs.new-version }}" || echo "No changes to commit."
                  git push origin main

            - name: Clean up workspace
              run: |
                  cd ~/actions-runner/_work
                  rm -rf nanumsa-k8s
