name: nanumsa CI kustomize

on:
    workflow_call:
        inputs:
            image-name:
                description: "Name of the image to be updated"
                required: true
                default: "nanumsa-front"
                type: string

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Check previous job status
              run: |
                  echo "This job is being executed for Kustomization update"

            - name: Setup Kustomize
              uses: imranismail/setup-kustomize@v1

            - name: Checkout Kustomize repository
              uses: actions/checkout@v2

            - name: Checkout B Project repository
              uses: actions/checkout@v2
              with:
                  repository: SmileMeeso/nanumsa-k8s
                  path: /home/ubuntu/nanumsa/k8s

            - name: Update k8s Kustomization file
              run: |
                  cd /home/ubuntu/nanumsa/k8s
                  sed -i "s/newTag: .*/newTag: \"$new_tag\"/" kustomization/kustomization.yaml
                  sed -i "s/name: .*/name: \"SmileMeeso/${{ inputs.image-name }}\"/" kustomization/kustomization.yaml
                  echo "Updated kustomization.yaml with newTag: $new_tag"

            - name: Commit changes
              run: |
                  cd /home/ubuntu/nanumsa/k8s
                  git config user.name ${{ secrets.USER_NAME }}
                  git config user.email ${{ secrets.EMAIL }}
                  git commit -am "Update Kustomization newTag to ${{ env.new_tag }}" || echo "No changes to commit."
                  git push
