name: nanumsa CI kustomize

on:
    workflow_call:
        inputs:
            image-name:
                description: "Name of the image to be updated"
                required: true
                default: "nanumsa-front"
                type: string
            new-version:
                description: "New Deploy Version"
                required: true
                default: "0.0.0"
                type: string

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Setup Kustomize
              uses: imranismail/setup-kustomize@v1

            - name: Checkout Kustomize repository
              uses: actions/checkout@v2

            - name: Checkout k8s Project repository
              uses: actions/checkout@v4
              with:
                  repository: SmileMeeso/nanumsa-k8s
                  path: nanumsa-k8s

            - name: Create kustomization.yaml
              run: |
                  cd nanumsa-k8s

                  image_name="${{ inputs.image-name }}"
                  folder_name="${image_name/nanumsa-/}"

                  echo "resources:" > kustomization.yaml
                  echo "  - $folder_name/deployment.yaml" >> kustomization.yaml
                  echo "patchesStrategicMerge:" >> kustomization.yaml
                  echo "  - patch.yaml" >> kustomization.yaml
                  echo "Created kustomization.yaml"
                  cat kustomization.yaml

            - name: Create patch.yaml
              run: |
                  cd nanumsa-k8s
                  echo "apiVersion: apps/v1" > patch.yaml
                  echo "kind: Deployment" >> patch.yaml
                  echo "metadata:" >> patch.yaml
                  echo "  name: ${{ inputs.image-name }}" >> patch.yaml
                  echo "spec:" >> patch.yaml
                  echo "  template:" >> patch.yaml
                  echo "    metadata:" >> patch.yaml
                  echo "      annotations:" >> patch.yaml
                  echo "        version: '${{ inputs.new-version }}'" >> patch.yaml
                  cat patch.yaml
                  echo "Created patch.yaml"

            - name: Apply Kustomization
              run: |
                  cd nanumsa-k8s
                  kubectl apply -k .

            - uses: actions/checkout@v2
              with:
                  repository: SmileMeeso/nanumsa-k8s
                  ref: "main"
                  token: ${{ secrets.PUSH_K8S_TOKEN }}

            - name: test
              run: |
                  echo "secret: ${{ secrets.PUSH_K8S_TOKEN }}"

            - name: Commit changes
              run: |
                  cd nanumsa-k8s
                  git config user.name ${{ secrets.USER_NAME }}
                  git config user.email ${{ secrets.EMAIL }}
                  git commit -m "Update Kustomization with new version: ${{ inputs.new-version }}" || echo "No changes to commit."
                  git push origin main

            - name: Clean up workspace
              run: |
                  cd ~/actions-runner/_work
                  rm -rf nanumsa-k8s
